version: '3.1'
services:
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
              MYSQL_DATABASE: db
              MYSQL_ROOT_PASSWORD: moha 
              MYSQL_PASSWORD: moha
      ports: 
              - "3306:3306"
      volumes:
              #- ./dump:/docker-entrypoint-initdb.d
              - ./mysql/schemas:/var/lib/mysql
      networks:
              - default
  laravel-prod:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 8300:80
      volumes:
        - ./laravel-app:/var/www/
        - ./laravel-app/public:/var/www/html
      depends_on:
        - db
      networks:
        - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - 8000:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: moha
        MYSQL_ROOT_PASSWORD: moha

volumes:
    persistent: